bin/Merge_Sort.exe: lib/Merge_Sort.o lib/Main_Test.o
	g++ lib/Merge_Sort.o lib/Main_Test.o -o bin/Merge_Sort.exe

lib/Merge_Sort.o: src/Merge_Sort.cpp
	g++ -c src/Merge_Sort.cpp -o lib/Merge_Sort.o

lib/Main_Test.o: src/Main_Test.cpp
	g++ -c src/Main_Test.cpp -o lib/Main_Test.o
